import { Generator, getConfig } from "@tanstack/router-generator";

// Regenerate src/routeTree.gen.ts without booting Vite. The file is
// git-ignored and generated by the tanstackStart() plugin at dev/build time;
// this mirrors that generation so `tsc --noEmit` can resolve route types in CI.
const root = new URL("..", import.meta.url).pathname;

const config = getConfig({ target: "react" }, root);
const generator = new Generator({ config, root });

await generator.run();
