export const productionCallStacks = {
  curatorAuthoring: [
    "HTTP edge",
    "TenantDataAccess",
    "ModelRouter",
    "ToolResolver",
    "SkillStore",
    "ArtifactStore",
    "CuratorAgent",
    "TenantDataAccess.batch",
  ],
  dispatch: [
    "HTTP edge",
    "TenantDataAccess",
    "ToolResolver",
    "SkillStore",
    "McpEgressPolicy",
    "ModelRouter",
    "ThreadAgent",
    "ArtifactStore",
    "ChannelHub",
    "WorkspaceHub",
  ],
  scheduledRun: [
    "Cloudflare scheduler",
    "ThreadAgent",
    "ToolResolver",
    "SkillStore",
    "McpEgressPolicy",
    "ModelRouter",
    "ArtifactStore",
    "ChannelHub",
    "WorkspaceHub",
  ],
} as const;

export const testCallStacks = {
  curatorAuthoring: [
    "test caller",
    "MemoryTenantDataAccess",
    "MemoryModelRouter",
    "MemoryToolResolver",
    "MemorySkillStore",
    "MemoryArtifactStore",
    "MemoryCuratorAgent",
    "MemoryTenantDataAccess.batch",
  ],
  dispatch: [
    "test caller",
    "MemoryTenantDataAccess",
    "MemoryToolResolver",
    "MemorySkillStore",
    "MemoryMcpEgressPolicy",
    "MemoryModelRouter",
    "MemoryThreadAgent",
    "MemoryArtifactStore",
    "MemoryChannelHub",
    "MemoryWorkspaceHub",
  ],
  scheduledRun: [
    "test scheduler",
    "MemoryThreadAgent",
    "MemoryToolResolver",
    "MemorySkillStore",
    "MemoryMcpEgressPolicy",
    "MemoryModelRouter",
    "MemoryArtifactStore",
    "MemoryChannelHub",
    "MemoryWorkspaceHub",
  ],
} as const;
